name: build-manual
permissions: {}
on:
  pull_request:
  workflow_dispatch:
    inputs:
      recipe:
        description: Recipe file to build
        type: string
        required: true
        default: images/osmium.yml
      branch:
        description: Branch to build from
        type: string
        required: true
        default: main
      chunkah:
        description: Use chunked OCI image (chunkah)
        type: boolean
        default: true
jobs:
  bluebuild:
    name: Build osmium
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-single.yml
    with:
      recipe: ${{ inputs.recipe || 'images/osmium.yml' }}
      branch: ${{ inputs.branch || github.head_ref || github.ref }}
      chunkah: ${{ github.event_name == 'pull_request' && true || inputs.chunkah }}
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
