name: build-one
permissions: {}
on:
  workflow_call:
    inputs:
      recipe:
        type: string
        required: true
      branch:
        type: string
        required: false
      chunkah:
        type: boolean
        required: false
        default: true
    secrets:
      SIGNING_SECRET:
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.recipe }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build osmium
    runs-on: ubuntu-26.04
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.branch || github.ref }}
      - name: Build osmium
        uses: blue-build/github-action@836161eb076426a451e6a0054f722b1153b8b3ad # v1.12.0
        with:
          cli_version: v0.9.37
          recipe: ${{ inputs.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          maximize_build_space: true
          squash: true
          chunkah: ${{ inputs.chunkah }}
          max_layers: 128
          skip_checkout: true
          use_cache: false
          retry_push_count: 3
          verify_install: true